/* 
**  mod_reqcpulog.c -- Apache sample reqcpulog module
**  [Autogenerated via ``apxs -n reqcpulog -g'']
*/ 

#include "httpd.h"
#include "http_core.h"
#include "http_config.h"
#include "http_connection.h"
#include "http_protocol.h"
#include "ap_config.h"
#include "mpm.h"
#include "apr_portable.h"
#include "apr_strings.h"
#include "apr_tables.h"

#define APR_WANT_STRFUNC
#include "apr_want.h"

#ifndef PREFORK_MPM
#error "mod_reqcpulog only works with the prefork MPM"
#endif

#ifndef HAVE_TIMES
#error "mod_reqcpulog requires times(3) (HAVE_TIMES)"
#endif

#include <time.h>
#include <sys/times.h>

module AP_MODULE_DECLARE_DATA reqcpulog_module;

/* Start counting when we're finished reading the request. */
static int reqcpulog_post_read_request(request_rec *r)
{
    struct tms *start_time = apr_pcalloc(r->connection->pool, sizeof(*start_time));
    if (times(start_time) != (clock_t)-1)
        ap_set_module_config(r->connection->conn_config, &reqcpulog_module, start_time);
    return OK;
}

/* Store notes for used CPU. */
static int reqcpulog_log_transaction(request_rec *r)
{
    struct tms *start_time = ap_get_module_config(r->connection->conn_config,
                                                  &reqcpulog_module);
    struct tms finish_time;
    
    if (times(&finish_time) != (clock_t)-1 && start_time) {
        apr_table_set(r->notes, "reqcpulog-usercpu",
                      apr_itoa(r->pool, finish_time.tms_cutime - start_time->tms_cutime));
        apr_table_set(r->notes, "reqcpulog-syscpu",
                      apr_itoa(r->pool, finish_time.tms_cstime - start_time->tms_cstime));
    }
    
    return OK;
}

static void reqcpulog_register_hooks(apr_pool_t *p)
{
    ap_hook_post_read_request(reqcpulog_post_read_request, NULL, NULL, APR_HOOK_MIDDLE);
    ap_hook_log_transaction(reqcpulog_log_transaction, NULL, NULL, APR_HOOK_FIRST);
}

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA reqcpulog_module = {
    STANDARD20_MODULE_STUFF, 
    NULL,                  /* create per-dir    config structures */
    NULL,                  /* merge  per-dir    config structures */
    NULL,                  /* create per-server config structures */
    NULL,                  /* merge  per-server config structures */
    NULL,                  /* table of config file commands       */
    reqcpulog_register_hooks  /* register hooks                      */
};

